import {
  Connection,
  PublicKey,
  SystemProgram,
  Transaction,
  LAMPORTS_PER_SOL,
  ComputeBudgetProgram,
} from "@solana/web3.js";

/** Cluster used by the demo. Switch to "mainnet-beta" once programs are deployed. */
export const CLUSTER: "devnet" | "mainnet-beta" =
  (process.env.NEXT_PUBLIC_CLUSTER as "devnet" | "mainnet-beta") ?? "devnet";

/** Optional treasury address override. Defaults to self-transfer (lose only fee). */
export const ATLAS_TREASURY =
  process.env.NEXT_PUBLIC_ATLAS_TREASURY?.trim() || null;

export function explorerTxUrl(sig: string): string {
  const base = "https://solana.fm/tx/";
  const cluster = CLUSTER === "devnet" ? "?cluster=devnet-solana" : "";
  return `${base}${sig}${cluster}`;
}

export function explorerAddrUrl(addr: string): string {
  const base = "https://solana.fm/address/";
  const cluster = CLUSTER === "devnet" ? "?cluster=devnet-solana" : "";
  return `${base}${addr}${cluster}`;
}

/**
 * Build a deposit-style demo transaction.
 *
 * SOL transfer from `payer` to either:
 *   - configured ATLAS_TREASURY (if NEXT_PUBLIC_ATLAS_TREASURY is set), or
 *   - the payer themselves (no-op except network fee — safe for demos).
 *
 * Real deposit (Token-2022 USDC into the vault PDA) goes here once
 * `atlas_vault::deposit` ix builder is generated by Codama in Phase 2.
 */
export async function buildDepositTransaction(
  conn: Connection,
  payer: PublicKey,
  amountSol: number,
): Promise<Transaction> {
  if (!Number.isFinite(amountSol) || amountSol <= 0) {
    throw new Error("Amount must be a positive number");
  }
  const lamports = Math.floor(amountSol * LAMPORTS_PER_SOL);

  const dest = ATLAS_TREASURY ? new PublicKey(ATLAS_TREASURY) : payer;

  const { blockhash, lastValidBlockHeight } = await conn.getLatestBlockhash();

  const tx = new Transaction({
    feePayer: payer,
    blockhash,
    lastValidBlockHeight,
  });

  tx.add(
    ComputeBudgetProgram.setComputeUnitLimit({ units: 200_000 }),
    ComputeBudgetProgram.setComputeUnitPrice({ microLamports: 1_000 }),
    SystemProgram.transfer({
      fromPubkey: payer,
      toPubkey: dest,
      lamports,
    }),
  );

  return tx;
}

export function fmtSol(lamports: number | bigint | null | undefined, digits = 4): string {
  if (lamports == null) return "—";
  const n = typeof lamports === "bigint" ? Number(lamports) : lamports;
  return (n / LAMPORTS_PER_SOL).toLocaleString(undefined, {
    minimumFractionDigits: digits,
    maximumFractionDigits: digits,
  });
}

export function shortAddr(addr: string, head = 4, tail = 4): string {
  if (addr.length <= head + tail + 1) return addr;
  return `${addr.slice(0, head)}…${addr.slice(-tail)}`;
}
