[toolchain]
anchor_version = "0.32.1"
solana_version = "2.1.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
atlas_verifier = "A738nTHZKBpwHrPoHcwi9qrC8m7m17eXn2PzWix1ufR1"
atlas_registry = "5Pe99BkTVZrNQbNjTATJ6UT6owCZZZ1cJaoDdZEw3WEJ"
atlas_vault = "HejuE3SUKb2PT7WiCxzY9GFt8t3dToxVSB2DtT8JqCjG"
atlas_rebalancer = "4At18ooZgs7Sno83kGyKX1QptKqiWvfjZwZCBMcWKuAY"

[programs.devnet]
atlas_verifier = "A738nTHZKBpwHrPoHcwi9qrC8m7m17eXn2PzWix1ufR1"
atlas_registry = "5Pe99BkTVZrNQbNjTATJ6UT6owCZZZ1cJaoDdZEw3WEJ"
atlas_vault = "HejuE3SUKb2PT7WiCxzY9GFt8t3dToxVSB2DtT8JqCjG"
atlas_rebalancer = "4At18ooZgs7Sno83kGyKX1QptKqiWvfjZwZCBMcWKuAY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec mocha -t 1000000 tests/"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD"  # Kamino Lend

[[test.validator.clone]]
address = "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4"  # Jupiter Aggregator v6

[[test.validator.clone]]
address = "dRiftyHA39MWEi3m9aunc5MzRF1JYuBsbn6VPcn33UH"  # Drift v2
